//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GroupProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class frieght
    {
        public string itemID { get; set; }
        public float weight { get; set; }
        public float length { get; set; }
        public float width { get; set; }
        public float height { get; set; }
        public Nullable<float> value { get; set; }
    
        public virtual documentfreight documentfreight { get; set; }
    }
}
