//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GroupProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class invoice
    {
        public int invoiceID { get; set; }
        public string customerID { get; set; }
        public float totalDeliveryCost { get; set; }
        public string detail { get; set; }
        public string verification { get; set; }
        public string paymentMethod { get; set; }
    
        public virtual customer customer { get; set; }
    }
}
