//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GroupProject
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class edeEntities1 : DbContext
    {
        public edeEntities1()
            : base("name=edeEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<customer> customers { get; set; }
        public virtual DbSet<documentfreight> documentfreights { get; set; }
        public virtual DbSet<edeaccount> edeaccounts { get; set; }
        public virtual DbSet<frieght> frieghts { get; set; }
        public virtual DbSet<invoice> invoices { get; set; }
        public virtual DbSet<operationcenter> operationcenters { get; set; }
        public virtual DbSet<paymentgateway> paymentgateways { get; set; }
        public virtual DbSet<pickuporder> pickuporders { get; set; }
        public virtual DbSet<shipment> shipments { get; set; }
        public virtual DbSet<staff> staffs { get; set; }
        public virtual DbSet<vehicle> vehicles { get; set; }
    }
}
