//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GroupProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class shipment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public shipment()
        {
            this.documentfreights = new HashSet<documentfreight>();
        }
    
        public string shipmentNo { get; set; }
        public string sender { get; set; }
        public string receiver { get; set; }
        public string centerID { get; set; }
        public string gatewayID { get; set; }
        public System.DateTime date { get; set; }
        public string insurance { get; set; }
        public string commodityCode { get; set; }
    
        public virtual customer customer { get; set; }
        public virtual customer customer1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<documentfreight> documentfreights { get; set; }
        public virtual operationcenter operationcenter { get; set; }
        public virtual paymentgateway paymentgateway { get; set; }
    }
}
