//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GroupProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class staff
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public staff()
        {
            this.vehicles = new HashSet<vehicle>();
        }
    
        public string staffID { get; set; }
        public System.DateTime dob { get; set; }
        public string centerID { get; set; }
        public string nationalIDNum { get; set; }
        public string contactPhoneNum { get; set; }
        public string department { get; set; }
        public string position { get; set; }
        public Nullable<int> salary { get; set; }
        public Nullable<int> officePhoneNum { get; set; }
    
        public virtual operationcenter operationcenter { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vehicle> vehicles { get; set; }
    }
}
